package dev.tower.docgen;

import dev.tower.application.documentation.DocumentSection;
import dev.tower.application.documentation.DocumentTemplate;

import java.util.List;

/**
 * The closing note every rendered release document carries.
 *
 * <p>Shared by the Markdown and HTML renderers so the two cannot drift into
 * saying different things about the same document.
 *
 * <p>Two claims, and neither is decoration:
 *
 * <ul>
 *   <li>The document is a view of the Canonical Model and not a source of truth
 *       (BR-07). No template can remove this — {@link DocumentSection} does not
 *       offer it as a choice, which is what makes it unremovable rather than
 *       merely discouraged.
 *   <li>Which template produced the document, and what that template leaves out.
 *       This is the honesty rule the renderers already follow for empty
 *       sections, applied to the template itself. Without it a reader cannot
 *       tell "no validation Iterations have been recorded" from "Iterations were
 *       not included in this document" — and those two lead to opposite
 *       decisions about whether a release is ready.
 * </ul>
 */
final class DocumentProvenance {

    private DocumentProvenance() {
    }

    /**
     * @param separator what joins the two sentences — a newline for Markdown,
     *                  a space for HTML, so each format wraps the way it should
     */
    static String note(DocumentTemplate template, String separator) {
        return origin(template) + separator
                + "This document is a view of that model, not a source of truth (BR-07), "
                + "and can be regenerated at any time.";
    }

    private static String origin(DocumentTemplate template) {
        if (template.isBuiltIn()) {
            return "Generated by Tower from the Canonical Model.";
        }
        String origin = "Generated by Tower from the Canonical Model using the \""
                + template.name() + "\" template";
        List<DocumentSection> omitted = template.omitted();
        if (omitted.isEmpty()) {
            return origin + ".";
        }
        return origin + ", which does not include " + list(omitted) + ".";
    }

    /** "A", "A and B", "A, B and C" — in declaration order, so never in doubt. */
    private static String list(List<DocumentSection> sections) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < sections.size(); i++) {
            if (i > 0) {
                out.append(i == sections.size() - 1 ? " and " : ", ");
            }
            out.append(sections.get(i).heading());
        }
        return out.toString();
    }
}
